import numpy as np
import pandas as pd

from dpmm.metrics.base import Metric


class QuerySimilarity(Metric):
    metric_name = "query_similarity"

    def __init__(self, max_dim=3, min_dim=1, n_queries=100, max_ratio=10):
        self.max_dim = max_dim
        self.min_dim = min_dim
        self.n_queries = n_queries
        self.max_ratio = max_ratio

    def get_queries(self, domain, n_queries):
        return pd.concat(
            [
                pd.DataFrame(
                    {
                        f"{col}_{idx}": arr
                        for col in domain
                        if "lower" in domain[col]
                        for idx, arr in enumerate(
                            np.sort(
                                np.random.uniform(
                                    domain[col]["lower"],
                                    domain[col]["upper"],
                                    size=(2, n_queries),
                                ),
                                axis=0,
                            )
                        )
                    }
                ),
                pd.DataFrame(
                    {
                        col: np.random.choice(domain[col]["categories"], size=n_queries)
                        for col in domain
                        if "categories" in domain[col]
                    }
                ),
            ],
            axis=1,
        )

    def match_query(self, query_cols, query, data):
        matches = {
            col: (
                (
                    data[col] == query[col]
                    if pd.notnull(query[col])
                    else data[col].isna()
                )
                if col in query.index
                else (
                    (data[col] >= query[f"{col}_0"]) & (data[col] <= query[f"{col}_1"])
                )
            )
            for col in query_cols
        }
        return np.sum(np.prod(list(matches.values()), axis=0), axis=0)

    def __call__(
        self,
        synthetic_data: pd.DataFrame,
        source_data: pd.DataFrame,
        test_data: pd.DataFrame = None,
        domain: dict = None,
    ):
        """
        Computes the query similarity metric between synthetic and source data.

        Parameters:
            synthetic_data (pd.DataFrame): The synthetic data generated by the model.
            source_data (pd.DataFrame): The original source data.
            test_data (pd.DataFrame, optional): Unused in this metric.
            domain (dict, optional): Unused in this metric.

        Returns:
            float: The computed query similarity score.
        """

        if domain is None:
            domain = {
                col: (
                    {"lower": series.min(), "upper": series.max()}
                    if series.dtype.kind in "Mmfui"
                    else {"categories": series.unique().tolist()}
                )
                for col, series in source_data.items()
            }

        if self.max_dim is None:
            self.max_dim = min(source_data.shape[1], self.max_dim)

        max_queries = self.max_ratio * self.n_queries
        # per_dim = {(dim + 1): [] for dim in range(self.max_dim)}

        scores = []

        full_queries = self.get_queries(domain, max_queries)

        if self.max_dim is None:
            self.max_dim = source_data.shape[1]

        n_cols = np.random.randint(
            min(self.min_dim, source_data.shape[1]),
            min(self.max_dim, source_data.shape[1]) + 1,
            size=[max_queries],
        )

        query_count = 0
        for q_idx, query in full_queries.iterrows():
            query_cols = np.random.choice(
                source_data.columns.tolist(), size=n_cols[q_idx], replace=False
            )

            counts = [
                self.match_query(query_cols, query, data)
                for data in [source_data, synthetic_data]
            ]

            if counts[0] == 0:
                continue
            else:
                query_count += 1
                score = (min(counts)) / (max(counts))

            scores.append(score)
            # per_dim[len(query_cols)].append(score)

            if query_count == self.n_queries:
                break

        # per_dim = {dim: np.mean(dim_scores) for dim, dim_scores in per_dim.items()}
        return np.mean(scores)
